apiVersion: v1
kind: Service
metadata:
  name: temperature-service
spec:
  type: NodePort
  selector:
    app: temperature
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30100
