services:
  test_db:
    image: timescale/timescaledb:latest-pg16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: temperatures
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 10

  service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      test_db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password@test_db:5432/temperatures
      ENVIRONMENT: local
    volumes:
      - ./app:/usr/src/app:consistent
