version: 2.1

parameters:
  image:
    type: string
    default: default

jobs:
  test:
    machine:
      image: << pipeline.parameters.image >>
    steps:
      - checkout
      - run:
          name: Build image
          command: make build
      - run:
          name: Run tests
          command: make test

  deploy:
    machine:
      image: << pipeline.parameters.image >>
    steps:
      - checkout
      - run:
          name: Deploy
          command: echo "Deployed to production!"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
